<?php

use Illuminate\Database\Seeder;

class InvoiceDetailTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('invoice_detail')->delete();
        
        \DB::table('invoice_detail')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ref_id' => 1,
                'item_id' => 1,
                'item_code' => 'ច1',
                'title' => 'ចិញ្ចៀនប្រុស',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 3.0,
                'cost' => 0.0,
                'price' => 1200.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 04:30:27',
                'updated_at' => '2017-09-11 04:30:27',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'ref_id' => 2,
                'item_id' => 6,
                'item_code' => 'ច2',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 2.0,
                'cost' => 0.0,
                'price' => 3520.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 04:36:15',
                'updated_at' => '2017-09-11 04:36:15',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'ref_id' => 2,
                'item_id' => 8,
                'item_code' => 'ច4',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 850.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 04:36:15',
                'updated_at' => '2017-09-11 04:36:15',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'ref_id' => 3,
                'item_id' => 1,
                'item_code' => 'ច1',
                'title' => 'ចិញ្ចៀនប្រុស',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 1200.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 04:44:55',
                'updated_at' => '2017-09-11 04:44:55',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'ref_id' => 3,
                'item_id' => 6,
                'item_code' => 'ច2',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 3520.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 04:44:56',
                'updated_at' => '2017-09-11 04:44:56',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'ref_id' => 3,
                'item_id' => 8,
                'item_code' => 'ច4',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 850.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 04:44:56',
                'updated_at' => '2017-09-11 04:44:56',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'ref_id' => 3,
                'item_id' => 9,
                'item_code' => 'ច5',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 500.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 04:44:56',
                'updated_at' => '2017-09-11 04:44:56',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'ref_id' => 4,
                'item_id' => 6,
                'item_code' => 'ច2',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 2.0,
                'cost' => 0.0,
                'price' => 3520.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 04:45:14',
                'updated_at' => '2017-09-11 04:45:14',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'ref_id' => 4,
                'item_id' => 8,
                'item_code' => 'ច4',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 850.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 04:45:14',
                'updated_at' => '2017-09-11 04:45:14',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'ref_id' => 5,
                'item_id' => 6,
                'item_code' => 'ច2',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 3.0,
                'cost' => 0.0,
                'price' => 3520.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 06:07:13',
                'updated_at' => '2017-09-11 06:07:13',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'ref_id' => 5,
                'item_id' => 8,
                'item_code' => 'ច4',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 3.0,
                'cost' => 0.0,
                'price' => 850.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 06:07:13',
                'updated_at' => '2017-09-11 06:07:13',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'ref_id' => 6,
                'item_id' => 1,
                'item_code' => 'ច1',
                'title' => 'ចិញ្ចៀនប្រុស',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 7.0,
                'cost' => 0.0,
                'price' => 1200.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 06:09:27',
                'updated_at' => '2017-09-11 06:09:27',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'ref_id' => 7,
                'item_id' => 6,
                'item_code' => 'ច2',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 5.0,
                'cost' => 0.0,
                'price' => 3520.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 06:39:47',
                'updated_at' => '2017-09-11 06:39:47',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'ref_id' => 8,
                'item_id' => 1,
                'item_code' => 'ច1',
                'title' => 'ចិញ្ចៀនប្រុស',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 1200.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 13:12:32',
                'updated_at' => '2017-09-11 13:12:32',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'ref_id' => 8,
                'item_id' => 6,
                'item_code' => 'ច2',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 3520.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 13:12:32',
                'updated_at' => '2017-09-11 13:12:32',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'ref_id' => 8,
                'item_id' => 8,
                'item_code' => 'ច4',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 850.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 13:12:32',
                'updated_at' => '2017-09-11 13:12:32',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'ref_id' => 9,
                'item_id' => 1,
                'item_code' => 'ច1',
                'title' => 'ចិញ្ចៀនប្រុស',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 1200.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 13:13:48',
                'updated_at' => '2017-09-11 13:13:48',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'ref_id' => 9,
                'item_id' => 6,
                'item_code' => 'ច2',
                'title' => 'ចិញ្ចៀនស្រី',
                'unit' => '5',
                'num_qty' => 1.0,
                'qty' => 1.0,
                'cost' => 0.0,
                'price' => 3520.0,
                'discount' => 0.0,
                'note' => '',
                'item_detail' => '[]',
                'created_at' => '2017-09-11 13:13:49',
                'updated_at' => '2017-09-11 13:13:49',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}