<?php

use Illuminate\Database\Seeder;

class InvoiceTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('invoice')->delete();
        
        \DB::table('invoice')->insert(array (
            0 => 
            array (
                'id' => 1,
                'invoice_number' => 'SALE/POS/1708/00008',
                '_date_' => '2017-09-11',
                'customer_id' => 1,
                'description' => NULL,
                'customer_note' => 'customer not detail',
                'payment_note' => NULL,
                'deposit' => NULL,
                'total_amt' => 3600.0,
                'total_discount' => NULL,
                'total_payable' => 3500.0,
                'paid' => 8500.0,
                'user_id' => NULL,
                'status' => 'PENDING',
                'complete_date' => NULL,
                'complete_price' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'invoice_number' => 'SALE/POS/1708/00008',
                '_date_' => '2017-09-11',
                'customer_id' => 1,
                'description' => NULL,
                'customer_note' => 'customer not detail',
                'payment_note' => NULL,
                'deposit' => NULL,
                'total_amt' => 7890.0,
                'total_discount' => NULL,
                'total_payable' => 7890.0,
                'paid' => 15780.0,
                'user_id' => NULL,
                'status' => 'PENDING',
                'complete_date' => NULL,
                'complete_price' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'invoice_number' => 'SALE/POS/1708/00008',
                '_date_' => '2017-09-11',
                'customer_id' => 1,
                'description' => NULL,
                'customer_note' => 'customer not detail',
                'payment_note' => NULL,
                'deposit' => NULL,
                'total_amt' => 6070.0,
                'total_discount' => NULL,
                'total_payable' => 5970.0,
                'paid' => 5970.0,
                'user_id' => NULL,
                'status' => 'PENDING',
                'complete_date' => NULL,
                'complete_price' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'invoice_number' => 'SALE/POS/1708/00008',
                '_date_' => '2017-09-11',
                'customer_id' => 1,
                'description' => NULL,
                'customer_note' => 'customer not detail',
                'payment_note' => NULL,
                'deposit' => NULL,
                'total_amt' => 7890.0,
                'total_discount' => NULL,
                'total_payable' => 7890.0,
                'paid' => 15050.0,
                'user_id' => NULL,
                'status' => 'PENDING',
                'complete_date' => NULL,
                'complete_price' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'invoice_number' => 'SALE/POS/1708/00008',
                '_date_' => '2017-09-11',
                'customer_id' => 1,
                'description' => NULL,
                'customer_note' => 'customer not detail',
                'payment_note' => NULL,
                'deposit' => NULL,
                'total_amt' => 13110.0,
                'total_discount' => NULL,
                'total_payable' => 13110.0,
                'paid' => 13110.0,
                'user_id' => NULL,
                'status' => 'PENDING',
                'complete_date' => NULL,
                'complete_price' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'invoice_number' => 'SALE/POS/1708/00008',
                '_date_' => '2017-09-11',
                'customer_id' => 1,
                'description' => NULL,
                'customer_note' => 'customer not detail',
                'payment_note' => NULL,
                'deposit' => NULL,
                'total_amt' => 8400.0,
                'total_discount' => NULL,
                'total_payable' => 8300.0,
                'paid' => 8300.0,
                'user_id' => NULL,
                'status' => 'PENDING',
                'complete_date' => NULL,
                'complete_price' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'invoice_number' => 'SALE/POS/1708/00008',
                '_date_' => '2017-09-11',
                'customer_id' => 1,
                'description' => NULL,
                'customer_note' => 'customer not detail',
                'payment_note' => NULL,
                'deposit' => NULL,
                'total_amt' => 17600.0,
                'total_discount' => NULL,
                'total_payable' => 17400.0,
                'paid' => 17400.0,
                'user_id' => NULL,
                'status' => 'PENDING',
                'complete_date' => NULL,
                'complete_price' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'invoice_number' => 'SALE/POS/1708/00008',
                '_date_' => '2017-09-11',
                'customer_id' => 1,
                'description' => NULL,
                'customer_note' => 'customer not detail',
                'payment_note' => NULL,
                'deposit' => NULL,
                'total_amt' => 5570.0,
                'total_discount' => NULL,
                'total_payable' => 5470.0,
                'paid' => 5470.0,
                'user_id' => NULL,
                'status' => 'PENDING',
                'complete_date' => NULL,
                'complete_price' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'invoice_number' => 'SALE/POS/1708/00008',
                '_date_' => '2017-09-11',
                'customer_id' => 1,
                'description' => NULL,
                'customer_note' => 'customer not detail',
                'payment_note' => NULL,
                'deposit' => NULL,
                'total_amt' => 4720.0,
                'total_discount' => NULL,
                'total_payable' => 4620.0,
                'paid' => 4620.0,
                'user_id' => NULL,
                'status' => 'PENDING',
                'complete_date' => NULL,
                'complete_price' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}